# Generated by Django 4.1 on 2022-08-04 19:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.FileField(upload_to=users.models.avatar_upload_handler),
        ),
    ]
