# Generated by Django 4.1 on 2022-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="challenge",
            name="hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="challenge",
            name="minutes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
