# Generated by Django 4.1 on 2022-08-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0002_challenge_days_challenge_hours_challenge_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="actual_end_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="minutes",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
